# Form implementation generated from reading ui file 'c:\Users\sufya\Desktop\db_updated\BookingDetails.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(525, 439)
        self.name = QtWidgets.QLabel(parent=Dialog)
        self.name.setGeometry(QtCore.QRect(20, 30, 51, 21))
        self.name.setObjectName("name")
        self.hall_name = QtWidgets.QLabel(parent=Dialog)
        self.hall_name.setGeometry(QtCore.QRect(20, 180, 31, 16))
        self.hall_name.setObjectName("hall_name")
        self.contact_no = QtWidgets.QLabel(parent=Dialog)
        self.contact_no.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.contact_no.setObjectName("contact_no")
        self.hall_price = QtWidgets.QLabel(parent=Dialog)
        self.hall_price.setGeometry(QtCore.QRect(20, 230, 31, 16))
        self.hall_price.setObjectName("hall_price")
        self.Time = QtWidgets.QLabel(parent=Dialog)
        self.Time.setGeometry(QtCore.QRect(20, 290, 31, 16))
        self.Time.setObjectName("Time")
        self.lol = QtWidgets.QLabel(parent=Dialog)
        self.lol.setGeometry(QtCore.QRect(20, 120, 31, 21))
        self.lol.setObjectName("lol")
        self.CustomerName = QtWidgets.QLineEdit(parent=Dialog)
        self.CustomerName.setGeometry(QtCore.QRect(80, 20, 381, 31))
        self.CustomerName.setObjectName("CustomerName")
        self.ContactNo = QtWidgets.QLineEdit(parent=Dialog)
        self.ContactNo.setGeometry(QtCore.QRect(80, 70, 381, 31))
        self.ContactNo.setObjectName("ContactNo")
        self.cnic = QtWidgets.QLineEdit(parent=Dialog)
        self.cnic.setGeometry(QtCore.QRect(130, 110, 331, 31))
        self.cnic.setObjectName("cnic")
        self.HallName = QtWidgets.QLineEdit(parent=Dialog)
        self.HallName.setGeometry(QtCore.QRect(80, 170, 381, 31))
        self.HallName.setObjectName("HallName")
        self.Price = QtWidgets.QLineEdit(parent=Dialog)
        self.Price.setGeometry(QtCore.QRect(80, 220, 381, 31))
        self.Price.setObjectName("Price")
        self.Day = QtWidgets.QRadioButton(parent=Dialog)
        self.Day.setGeometry(QtCore.QRect(90, 290, 81, 21))
        self.Day.setObjectName("Day")
        self.Night = QtWidgets.QRadioButton(parent=Dialog)
        self.Night.setGeometry(QtCore.QRect(180, 290, 81, 21))
        self.Night.setObjectName("Night")
        self.updatebutton = QtWidgets.QPushButton(parent=Dialog)
        self.updatebutton.setGeometry(QtCore.QRect(340, 290, 71, 21))
        self.updatebutton.setObjectName("updatebutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.name.setText(_translate("Dialog", "Name"))
        self.hall_name.setText(_translate("Dialog", "Hall:"))
        self.contact_no.setText(_translate("Dialog", "Contact No."))
        self.hall_price.setText(_translate("Dialog", "Price:"))
        self.Time.setText(_translate("Dialog", "Time:"))
        self.lol.setText(_translate("Dialog", "CNIC:"))
        self.Day.setText(_translate("Dialog", "Day"))
        self.Night.setText(_translate("Dialog", "Night"))
        self.updatebutton.setText(_translate("Dialog", "Update"))
