# Form implementation generated from reading ui file 'c:\Users\sufya\Desktop\db_updated\Dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 673)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.user_details = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.user_details.setGeometry(QtCore.QRect(30, 70, 581, 161))
        self.user_details.setObjectName("user_details")
        self.user_name = QtWidgets.QLabel(parent=self.user_details)
        self.user_name.setGeometry(QtCore.QRect(10, 40, 51, 21))
        self.user_name.setObjectName("user_name")
        self.user_type = QtWidgets.QLabel(parent=self.user_details)
        self.user_type.setGeometry(QtCore.QRect(0, 100, 81, 21))
        self.user_type.setObjectName("user_type")
        self.CustName = QtWidgets.QLineEdit(parent=self.user_details)
        self.CustName.setGeometry(QtCore.QRect(70, 30, 461, 41))
        self.CustName.setObjectName("CustName")
        self.UserType = QtWidgets.QLineEdit(parent=self.user_details)
        self.UserType.setGeometry(QtCore.QRect(70, 90, 461, 41))
        self.UserType.setObjectName("UserType")
        self.acc_settings = QtWidgets.QPushButton(parent=self.centralwidget)
        self.acc_settings.setGeometry(QtCore.QRect(480, 300, 161, 41))
        self.acc_settings.setObjectName("acc_settings")
        self.book_a_hall = QtWidgets.QPushButton(parent=self.centralwidget)
        self.book_a_hall.setGeometry(QtCore.QRect(50, 300, 151, 41))
        self.book_a_hall.setObjectName("book_a_hall")
        self.my_bookings = QtWidgets.QPushButton(parent=self.centralwidget)
        self.my_bookings.setGeometry(QtCore.QRect(50, 350, 151, 41))
        self.my_bookings.setObjectName("my_bookings")
        self.close_d = QtWidgets.QPushButton(parent=self.centralwidget)
        self.close_d.setGeometry(QtCore.QRect(50, 490, 631, 41))
        self.close_d.setObjectName("close_d")
        self.privacy_policy = QtWidgets.QPushButton(parent=self.centralwidget)
        self.privacy_policy.setGeometry(QtCore.QRect(480, 350, 161, 41))
        self.privacy_policy.setObjectName("privacy_policy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.user_details.setTitle(_translate("MainWindow", "User Details"))
        self.user_name.setText(_translate("MainWindow", "Name"))
        self.user_type.setText(_translate("MainWindow", "User Type:"))
        self.UserType.setText(_translate("MainWindow", "Customer"))
        self.acc_settings.setText(_translate("MainWindow", "Account Settings"))
        self.book_a_hall.setText(_translate("MainWindow", "Book a Hall"))
        self.my_bookings.setText(_translate("MainWindow", "My Bookings"))
        self.close_d.setText(_translate("MainWindow", "Close"))
        self.privacy_policy.setText(_translate("MainWindow", "Privacy Policy"))
