# Form implementation generated from reading ui file 'c:\Users\sufya\Desktop\db_updated\dashboard_owner.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(496, 488)
        self.close_o = QtWidgets.QPushButton(parent=Form)
        self.close_o.setGeometry(QtCore.QRect(40, 390, 401, 41))
        self.close_o.setObjectName("close_o")
        self.my_halls = QtWidgets.QPushButton(parent=Form)
        self.my_halls.setGeometry(QtCore.QRect(20, 270, 171, 31))
        self.my_halls.setObjectName("my_halls")
        self.add_a_hall = QtWidgets.QPushButton(parent=Form)
        self.add_a_hall.setGeometry(QtCore.QRect(20, 200, 171, 51))
        self.add_a_hall.setObjectName("add_a_hall")
        self.acc_settings = QtWidgets.QPushButton(parent=Form)
        self.acc_settings.setGeometry(QtCore.QRect(300, 190, 171, 111))
        self.acc_settings.setObjectName("acc_settings")
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 451, 171))
        self.groupBox.setObjectName("groupBox")
        self.OName = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.OName.setGeometry(QtCore.QRect(100, 20, 311, 41))
        self.OName.setObjectName("OName")
        self.owner_name = QtWidgets.QLabel(parent=self.groupBox)
        self.owner_name.setGeometry(QtCore.QRect(20, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.owner_name.setFont(font)
        self.owner_name.setObjectName("owner_name")
        self.UserType = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.UserType.setGeometry(QtCore.QRect(100, 70, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UserType.setFont(font)
        self.UserType.setObjectName("UserType")
        self.user_type = QtWidgets.QLabel(parent=self.groupBox)
        self.user_type.setGeometry(QtCore.QRect(10, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_type.setFont(font)
        self.user_type.setObjectName("user_type")
        self.manage_hall_bookings = QtWidgets.QPushButton(parent=Form)
        self.manage_hall_bookings.setGeometry(QtCore.QRect(20, 320, 171, 51))
        self.manage_hall_bookings.setObjectName("manage_hall_bookings")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.close_o.setText(_translate("Form", "Close"))
        self.my_halls.setText(_translate("Form", "My Halls"))
        self.add_a_hall.setText(_translate("Form", "Add a Hall"))
        self.acc_settings.setText(_translate("Form", "Account Settings"))
        self.groupBox.setTitle(_translate("Form", "User Details"))
        self.owner_name.setText(_translate("Form", "Name"))
        self.UserType.setPlainText(_translate("Form", "Owner"))
        self.user_type.setText(_translate("Form", "User Type"))
        self.manage_hall_bookings.setText(_translate("Form", "Manage Hall Bookings"))
