# Form implementation generated from reading ui file 'c:\Users\sufya\Desktop\DBMS Project\Login_user.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(623, 466)
        self.CreateAcc = QtWidgets.QPushButton(parent=Form)
        self.CreateAcc.setGeometry(QtCore.QRect(450, 370, 121, 41))
        self.CreateAcc.setObjectName("CreateAcc")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CreateAcc.setText(_translate("Form", "Create Account"))
