# Form implementation generated from reading ui file 'c:\Users\sufya\Desktop\DBMS Project\LoginPage.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(619, 422)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(150, 10, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.User_id = QtWidgets.QLabel(parent=Form)
        self.User_id.setGeometry(QtCore.QRect(20, 90, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.User_id.setFont(font)
        self.User_id.setObjectName("User_id")
        self.EmailInput = QtWidgets.QPlainTextEdit(parent=Form)
        self.EmailInput.setGeometry(QtCore.QRect(130, 80, 361, 41))
        self.EmailInput.setObjectName("EmailInput")
        self.pw = QtWidgets.QLabel(parent=Form)
        self.pw.setGeometry(QtCore.QRect(20, 150, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pw.setFont(font)
        self.pw.setObjectName("pw")
        self.PasswordInput = QtWidgets.QPlainTextEdit(parent=Form)
        self.PasswordInput.setGeometry(QtCore.QRect(130, 140, 361, 41))
        self.PasswordInput.setObjectName("PasswordInput")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(150, 320, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.CustSignUp = QtWidgets.QPushButton(parent=Form)
        self.CustSignUp.setGeometry(QtCore.QRect(340, 330, 93, 28))
        self.CustSignUp.setObjectName("CustSignUp")
        self.Login = QtWidgets.QPushButton(parent=Form)
        self.Login.setGeometry(QtCore.QRect(460, 330, 93, 28))
        self.Login.setObjectName("Login")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "   VENUE MAESTRO"))
        self.User_id.setText(_translate("Form", "User Email"))
        self.pw.setText(_translate("Form", "Password"))
        self.label_4.setText(_translate("Form", "Don\'t have an account"))
        self.CustSignUp.setText(_translate("Form", "Sign Up"))
        self.Login.setText(_translate("Form", "Log In"))
