# Form implementation generated from reading ui file 'c:\Users\sufya\Desktop\db_updated_finall\My Bookings.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(792, 395)
        self.Booking_list = QtWidgets.QTableWidget(parent=Dialog)
        self.Booking_list.setGeometry(QtCore.QRect(60, 70, 651, 201))
        self.Booking_list.setObjectName("Booking_list")
        self.Booking_list.setColumnCount(6)
        self.Booking_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Booking_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Booking_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Booking_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Booking_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Booking_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Booking_list.setHorizontalHeaderItem(5, item)
        self.closee = QtWidgets.QPushButton(parent=Dialog)
        self.closee.setGeometry(QtCore.QRect(410, 290, 151, 31))
        self.closee.setObjectName("closee")
        self.delete_booking = QtWidgets.QPushButton(parent=Dialog)
        self.delete_booking.setGeometry(QtCore.QRect(170, 290, 161, 31))
        self.delete_booking.setObjectName("delete_booking")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.Booking_list.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Booking ID"))
        item = self.Booking_list.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Hall"))
        item = self.Booking_list.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Address"))
        item = self.Booking_list.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Date"))
        item = self.Booking_list.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Timeslot"))
        item = self.Booking_list.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Price"))
        self.closee.setText(_translate("Dialog", "Close"))
        self.delete_booking.setText(_translate("Dialog", "Delete Booking"))
