# Form implementation generated from reading ui file 'c:\Users\sufya\Desktop\DBMS Project\Type.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.UserTypeNext = QtWidgets.QPushButton(parent=Form)
        self.UserTypeNext.setGeometry(QtCore.QRect(270, 200, 93, 28))
        self.UserTypeNext.setObjectName("UserTypeNext")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.UserType = QtWidgets.QComboBox(parent=Form)
        self.UserType.setGeometry(QtCore.QRect(120, 110, 191, 31))
        self.UserType.setObjectName("UserType")
        self.UserType.addItem("")
        self.UserType.setItemText(0, "")
        self.UserType.addItem("")
        self.UserType.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.UserTypeNext.setText(_translate("Form", "Next"))
        self.label_5.setText(_translate("Form", "User Type"))
        self.UserType.setItemText(1, _translate("Form", "Owner"))
        self.UserType.setItemText(2, _translate("Form", "Customer"))
