# Form implementation generated from reading ui file 'c:\Users\sufya\Desktop\db_updated\ViewBookings.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(598, 342)
        self.bookings_table = QtWidgets.QTableWidget(parent=Dialog)
        self.bookings_table.setGeometry(QtCore.QRect(10, 10, 501, 192))
        self.bookings_table.setObjectName("bookings_table")
        self.bookings_table.setColumnCount(4)
        self.bookings_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.bookings_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookings_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookings_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookings_table.setHorizontalHeaderItem(3, item)
        self.edit_booking = QtWidgets.QPushButton(parent=Dialog)
        self.edit_booking.setGeometry(QtCore.QRect(10, 230, 101, 31))
        self.edit_booking.setObjectName("edit_booking")
        self.view_booking = QtWidgets.QPushButton(parent=Dialog)
        self.view_booking.setGeometry(QtCore.QRect(130, 230, 111, 31))
        self.view_booking.setObjectName("view_booking")
        self.close_view_bookings = QtWidgets.QPushButton(parent=Dialog)
        self.close_view_bookings.setGeometry(QtCore.QRect(410, 230, 101, 31))
        self.close_view_bookings.setObjectName("close_view_bookings")
        self.deletebooking = QtWidgets.QPushButton(parent=Dialog)
        self.deletebooking.setGeometry(QtCore.QRect(260, 230, 101, 31))
        self.deletebooking.setObjectName("deletebooking")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.bookings_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Booked by"))
        item = self.bookings_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Date"))
        item = self.bookings_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Time (Day/Night)"))
        item = self.bookings_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Price"))
        self.edit_booking.setText(_translate("Dialog", "Edit Booking"))
        self.view_booking.setText(_translate("Dialog", "View Booking"))
        self.close_view_bookings.setText(_translate("Dialog", "Close"))
        self.deletebooking.setText(_translate("Dialog", "Delete Booking"))
